version: "3"
services:
  e2e-test:
    image: golang:1.21
    env_file:
      - .env
    working_dir: /app
    environment:
      - TEMPLATE_DIR_PATH=/app/web/dist
      - WEBROOT=/app/webroot
      - DB_FILE_PATH=/app/data/wista-s3.db
      - TZ=Asia/Hong_Kong
    volumes:
      - .:/app
      - go-cache:/root/.cache/go-build
      - go-mod:/go/pkg/mod
    command: ["go", "test", "./pkg/", "-v", "-run", "TestE2E", "-timeout", "600s"]

volumes:
  go-cache:
  go-mod:
